### PR TITLE
Add bash variant of build_cmake/run_webserver bat files

### PR DESCRIPTION
**Pull request by qdel**

### CODE REVIEW

**Review by forderud — COMMENTED** [review]
Would you mind removing the main.cpp changes from this PR, so that we avoid bundling it with C++ code changes.

I have personal preference of submitting unrelated changes in separate PR's.

**Comment by qdel** [comment]
Made the change right now!

**Comment by forderud** [comment]
> Made the change right now!

Perfect! Would you also mind rebasing your PR on top of master, so that we get a more elegant git history?

**Comment by qdel** [comment]
> > Made the change right now!
> 
> Perfect! Would you also mind rebasing your PR on top of master, so that we get a more elegant git history?

Done

**Review by forderud — APPROVED** [review]
Thanks for making this repo more Linux/Mac friendly.

**Pull request merged**
