### PR TITLE
Use Ninja as default build tool

### PR DESCRIPTION
**Pull request by qdel**

### CODE REVIEW

**Comment by forderud** [comment]
Thanks a lot Quentin. Makes sense to me. Will test and review when I have time. However, I don't know if I will have time today.

**Comment by qdel** [comment]
> Thanks a lot Quentin. Makes sense to me. Will test and review when I have time. However, I don't know if I will have time today.

No rush, accept when you are available.

**Comment by forderud** [comment]
@qdel I've now tested your PR to confirm that the generated Docker image still "works" as before. Can you please rebase your PR on top of "master" before I merge?

**Comment by qdel** [comment]
Done

**Review by forderud — APPROVED** [review]

**Pull request merged**
