### PR TITLE
Revert "Stop limiting build parallelization"

### LINKED ISSUE #31: Docker image build failure
Problem observed when attempting to run `build_image.bat` on the "master" branch (with `DOCKER_BUILDKIT=false` to ease debugging):
```
[3554/10472] Building CXX object qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/qqmldomexternalitems.cpp.o
FAILED: qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/qqmldomexternalitems.cpp.o
/usr/bin/c++ -DQMLDOM_LIBRARY -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_QMLDOM_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_AS_CONST=1 -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_QMLCOMPILER_LIB -DQT_QMLINTEGRATION_LIB -DQT_QML_LIB -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/development/qt5_build_x64/qtdeclarative/src/qmldom/QmlDomPrivate_autogen/include -I/development/qt5_build_x64/qtbase/include -I/development/qt5_build_x64/qtbase/include/QtQmlDom -I/development/qt5/qtdeclarative/src/qmldom -I/development/qt5_build_x64/qtdeclarative/src/qmldom -I/development/qt5_build_x64/qtbase/include/QtQmlDom/6.5.0 -I/development/qt5_build_x64/qtbase/include/QtQmlDom/6.5.0/QtQmlDom -I/development/qt5_build_x64/qtdeclarative/src/qml -I/development/qt5_build_x64/qtbase/include/QtQml/6.5.0 -I/development/qt5_build_x64/qtbase/include/QtQml/6.5.0/QtQml -I/development/qt5_build_x64/qtbase/src/corelib -I/development/qt5_build_x64/qtbase/include/QtCore/6.5.0 -I/development/qt5_build_x64/qtbase/include/QtCore/6.5.0/QtCore -I/development/qt5_build_x64/qtbase/include/QtCore -I/development/qt5/qtbase/mkspecs/linux-g++ -I/development/qt5_build_x64/qtbase/include/QtQml -I/development/qt5_build_x64/qtbase/include/QtQmlIntegration -I/development/qt5/qtdeclarative/src/qmlintegration -I/development/qt5_build_x64/qtdeclarative/src/qmlintegration -I/development/qt5_build_x64/qtbase/include/QtNetwork -I/development/qt5_build_x64/qtbase/include/QtQmlCompiler -I/development/qt5_build_x64/qtdeclarative/src/qmlcompiler -I/development/qt5_build_x64/qtbase/include/QtQmlCompiler/6.5.0 -I/development/qt5_build_x64/qtbase/include/QtQmlCompiler/6.5.0/QtQmlCompiler -DNDEBUG -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -fPIC -Wsuggest-override -fcf-protection=full -std=c++17 -Winvalid-pch -include /development/qt5_build_x64/qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/cmake_pch.hxx -MD -MT qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/qqmldomexternalitems.cpp.o -MF qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/qqmldomexternalitems.cpp.o.d -o qtdeclarative/src/qmldom/CMakeFiles/QmlDomPrivate.dir/qqmldomexternalitems.cpp.o -c /development/qt5/qtdeclarative/src/qmldom/qqmldomexternalitems.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[3555/10472] Automatic MOC for target qtquickcontrols2fusionstyleplugin
```

Reproduced on a 12-core Win11 computer with 16GB RAM and Docker desktop installed in WSL2-mode using default settings.

### PR DESCRIPTION
**Pull request by forderud**
This reverts commit 3087c17a8d60d9244b02ccc875d9bd0e629f7808. Done to fix #31 which I suspect is due to some kind of "out of memory" problem.

### CODE REVIEW

**Comment by forderud** [comment]
@qdel Can you please review this PR?

**Comment by qdel** [comment]
Limiting cpu should not be made a configure time but by the host:

- I do want to use all my available cores
- Even if I have only 4 cores, if my wsl has access to 1G I will crash, and this patch won't help

**Comment by forderud** [comment]
> Limiting cpu should not be made a configure time but by the host:
> 
> * I do want to use all my available cores
> * Even if I have only 4 cores, if my wsl has access to 1G I will crash, and this patch won't help

Agree that this isn't the most elegant solution. However, it does seem to solve my build failure problem without having to manually tweak my docker settings. The rationale for reducing to just 4 build executors is that memory consumption should roughly grow linearly with the number of executors. This then places an upper bound on the memory consumption - regardless of how many CPU cores a system has.

Any suggestions for alternative approaches?

**Comment by qdel** [comment]
Adding a build-arg optional parameter could do the job like in this branch: https://github.com/qdel/QtWasm/tree/limit_jobs_cmake

**Comment by forderud** [comment]
Replaced by https://github.com/forderud/QtWasm/pull/33

**Pull request closed without merging**
